import pyttsx3
zesty=pyttsx3.init()
zesty.say('Welcome to the quiz')
zesty.runAndWait()
print('Welcome to the quiz')

zesty=pyttsx3.init()
zesty.say('Enter your name')
zesty.runAndWait()
name=input('Enter your name: \t \n')
zesty=pyttsx3.init()
zesty.say('Hello'+name)
zesty.runAndWait()
print('Hello',name)
zesty=pyttsx3.init()
zesty.say('Enter your age')
zesty.runAndWait()
age=int(input('Enter your age: \t \n'))
if age>=18:
    zesty=pyttsx3.init()
    zesty.say('You are eligible to play the quiz')
    zesty.runAndWait()
    print('You are eligible to play the quiz')
    zesty=pyttsx3.init()
    zesty.say('Please answer the following questions')
    zesty.runAndWait()
    print('Please answer the following questions')
    zesty=pyttsx3.init()
    zesty.say('Question 1: What is the capital of India?')
    zesty.runAndWait()
    print('Question 1: What is the capital of India?')
    answer1=input('Enter your answer: \t \n')
    if answer1=='New Delhi':
        zesty=pyttsx3.init()
        zesty.say('Correct answer')
        zesty.runAndWait()
        print('Correct answer')
    else:
        zesty=pyttsx3.init()
        zesty.say('Wrong answer')
        zesty.runAndWait()
        print('Wrong answer')
    zesty=pyttsx3.init()
    zesty.say('Question 2: What is the capital of Australia?')
    zesty.runAndWait()
    print('Question 2: What is the capital of Australia?')
    answer2=input('Enter your answer: \t \n')
    if answer2=='Canberra':
        zesty=pyttsx3.init()
        zesty.say('Correct answer')
        zesty.runAndWait()
        print('Correct answer')
    else:
        zesty=pyttsx3.init()
        zesty.say('Wrong answer')
        zesty.runAndWait()
        print('Wrong answer')
    zesty=pyttsx3.init()
    zesty.say('Question 3: What is the capital of France?')
    zesty.runAndWait()
    print('Question 3: What is the capital of France?')
    answer3=input('Enter your answer: \t \n')
    if answer3=='Paris':
        zesty=pyttsx3.init()
        zesty.say('Correct answer')
        zesty.runAndWait()
        print('Correct answer')
    else:
        zesty=pyttsx3.init()
        zesty.say('Wrong answer')
        zesty.runAndWait()
        print('Wrong answer')
    zesty=pyttsx3.init()
    zesty.say('Question 4: What is the capital of Japan?')
    zesty.runAndWait()
    print('Question 4: What is the capital of Japan?')
    answer4=input('Enter your answer: \t \n')
    if answer4=='Tokyo':
        zesty=pyttsx3.init()
        zesty.say('Correct answer')
        zesty.runAndWait()
        print('Correct answer')
    else:
        zesty=pyttsx3.init()
        zesty.say('Wrong answer')
        zesty.runAndWait()
        print('Wrong answer')
    zesty=pyttsx3.init()
    zesty.say('End of the quiz')    
    zesty.runAndWait()
    print('End of the quiz')
else:
    zesty=pyttsx3.init()
    zesty.say('You are not eligible to play the quiz')
    zesty.runAndWait()
    print('You are not eligible to play the quiz')
